# Generated by Django 3.0.5 on 2020-04-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislator',
            name='bioguide_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='birthdate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='legislator',
            name='congress_office',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='facebook_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='fax',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='feccandid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='first_elected',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='twitter_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='votesmart_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='webform',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='website',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='legislator',
            name='youtube_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='cid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='firstlast',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='gender',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='office',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='party',
            field=models.CharField(default='I', max_length=1),
        ),
    ]
