# Generated by Django 3.0.5 on 2020-04-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_secrets', '0004_auto_20200418_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgid', models.CharField(max_length=10)),
                ('orgname', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=200)),
                ('indivs', models.CharField(default='I', max_length=1)),
                ('pacs', models.CharField(default='', max_length=200)),
                ('soft', models.CharField(default='X', max_length=1)),
                ('tot527', models.CharField(default='', max_length=200)),
                ('dems', models.CharField(default='', max_length=200)),
                ('repubs', models.CharField(blank=True, max_length=200)),
                ('lobbying', models.CharField(blank=True, default='', max_length=200)),
                ('outside', models.CharField(blank=True, default='', max_length=200)),
                ('mems_invested', models.CharField(blank=True, default='', max_length=200)),
                ('gave_to_pac', models.CharField(blank=True, default='', max_length=200)),
                ('gave_to_party', models.CharField(blank=True, default='', max_length=200)),
                ('gave_to_527', models.CharField(blank=True, default='', max_length=200)),
                ('gave_to_cand', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
