# Generated by Django 3.0.5 on 2020-04-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_secrets', '0005_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.AlterField(
            model_name='legislator',
            name='cid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
