# Generated by Django 3.0.5 on 2020-04-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_secrets', '0006_auto_20200421_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislator',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True},
        ),
    ]
