# Generated by Django 3.0.5 on 2020-04-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_secrets', '0007_auto_20200421_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='indivs',
            field=models.CharField(default='I', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='soft',
            field=models.CharField(default='X', max_length=200),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(default='Unknown', max_length=200)),
                ('total', models.IntegerField(default=0)),
                ('pacs', models.IntegerField(default=0)),
                ('indivs', models.IntegerField(default=0)),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_secrets.Legislator')),
            ],
        ),
    ]
